<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aliciaTest5" nsURI="http://www.smith.edu//aliciaTest5aliciaTest5"
    nsPrefix="aliciaTest5">
  <eClassifiers xsi:type="ecore:EClass" name="AliciaLab">
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" upperBound="-1"
        eType="#//Project" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" upperBound="-1"
        eType="#//Student" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" eType="#//Student"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student"/>
</ecore:EPackage>
